"""empty message

Revision ID: 366eb8c2ee80
Revises: 334795237c6c
Create Date: 2020-01-14 14:19:08.913750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366eb8c2ee80'
down_revision = '334795237c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Projeto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Projeto')
    # ### end Alembic commands ###
